
p_browse_brick:
  path: '/browse/{sBrickId}'
  defaults:
    _controller: 'Combodo\iTop\Portal\Controller\BrowseBrickController::DisplayAction'


p_browse_brick_mode:
  path: '/browse/{sBrickId}/{sBrowseMode}'
  defaults:
    _controller: 'Combodo\iTop\Portal\Controller\BrowseBrickController::DisplayAction'


p_browse_brick_mode_list:
  path: '/browse/{sBrickId}/list/page/{iPageNumber}/show/{iListLength}'
  defaults:
    _controller: 'Combodo\iTop\Portal\Controller\BrowseBrickController::DisplayAction'
    sBrowseMode: list
    sDataLoading: lazy
    iPageNumber: 1
    iListLength: 20
  requirements:
    sBrowseMode: list
    iPageNumber: '\d+'
    iListLength: '\d+'


p_browse_brick_mode_tree:
  path: '/browse/{sBrickId}/tree/expand/{sLevelAlias}/{sNodeId}'
  defaults:
    _controller: 'Combodo\iTop\Portal\Controller\BrowseBrickController::DisplayAction'
    sBrowseMode: tree
    sDataLoading: lazy
    sNodeId: ~
  requirements:
    sBrowseMode: tree

